CREATE PROCEDURE SCHEMA.PROCEDURE_NAME(IN SOMETHING_COUNT INTEGER)
DYNAMIC RESULT SETS 1
LANGUAGE SQL
BEGIN
	SELECT SOME_ID_COL FROM SCHEMA.TABLE_NAME
	WHERE SOMETHING_COUNT < 100
END;

EXEC PROC_NAME

SELECT * FROM SCHEMA.TABLE_NAME
WHERE SOMETHING_COUNT < 100

CALL SCHEMA.PROCEDURE_NAME ('METRIC_SET', 'ANOTHER_METRIC_SET', 'ANOTHER_METRIC_SET', 2); --2 is a mode of store proc
